import { TargetLanguage } from '../types.ts';

export const TARGET_LANGUAGES: TargetLanguage[] = [
  { id: 'vi', name: 'Tiếng Việt', instructionName: 'Vietnamese (Tiếng Việt)' },
  { id: 'en', name: 'Tiếng Anh', instructionName: 'English (Tiếng Anh)' },
  { id: 'ar', name: 'Tiếng Ả Rập', instructionName: 'Arabic (Tiếng Ả Rập)' },
  { id: 'bg', name: 'Tiếng Bulgaria', instructionName: 'Bulgarian (Tiếng Bulgaria)' },
  { id: 'hr', name: 'Tiếng Croatia', instructionName: 'Croatian (Tiếng Croatia)' },
  { id: 'sr', name: 'Tiếng Serbia', instructionName: 'Serbian (Tiếng Serbia)' },
  { id: 'pl', name: 'Tiếng Ba Lan', instructionName: 'Polish (Tiếng Ba Lan)' },
  { id: 'cs', name: 'Tiếng Séc', instructionName: 'Czech (Tiếng Séc)' },
  { id: 'fr', name: 'Tiếng Pháp', instructionName: 'French (Tiếng Pháp)' },
  { id: 'de', name: 'Tiếng Đức', instructionName: 'German (Tiếng Đức)' },
  { id: 'es', name: 'Tiếng Tây Ban Nha', instructionName: 'Spanish (Tiếng Tây Ban Nha)' },
  { id: 'es-MX', name: 'Tiếng Tây Ban Nha (Mexico)', instructionName: 'Mexican Spanish (Tiếng Tây Ban Nha - Mexico)' },
  { id: 'pt', name: 'Tiếng Bồ Đào Nha', instructionName: 'Portuguese (Tiếng Bồ Đào Nha)' },
  { id: 'pt-BR', name: 'Tiếng Bồ Đào Nha (Brazil)', instructionName: 'Brazilian Portuguese (Tiếng Bồ Đào Nha - Brazil)' },
  { id: 'nl', name: 'Tiếng Hà Lan', instructionName: 'Dutch (Tiếng Hà Lan)' },
  { id: 'th', name: 'Tiếng Thái Lan', instructionName: 'Thai (Tiếng Thái Lan)' },
  { id: 'hi', name: 'Tiếng Ấn Độ', instructionName: 'Hindi (Tiếng Ấn Độ / Hindi)' },
  { id: 'da', name: 'Tiếng Đan Mạch', instructionName: 'Danish (Tiếng Đan Mạch)' },
  { id: 'no', name: 'Tiếng Na Uy', instructionName: 'Norwegian (Tiếng Na Uy)' },
  { id: 'hu', name: 'Tiếng Hungary', instructionName: 'Hungarian (Tiếng Hungary)' },
  { id: 'sl', name: 'Tiếng Slovenia', instructionName: 'Slovenian (Tiếng Slovenia)' },
  { id: 'ro', name: 'Tiếng Romania', instructionName: 'Romanian (Tiếng Romania)' },
  { id: 'fi', name: 'Tiếng Phần Lan', instructionName: 'Finnish (Tiếng Phần Lan)' },
  { id: 'sv', name: 'Tiếng Thụy Điển', instructionName: 'Swedish (Tiếng Thụy Điển)' },
  { id: 'it', name: 'Tiếng Ý', instructionName: 'Italian (Tiếng Ý)' },
  { id: 'de-AT', name: 'Tiếng Đức (Áo)', instructionName: 'Austrian German (Tiếng Đức - Áo)' },
  { id: 'ga', name: 'Tiếng Ireland', instructionName: 'Irish (Tiếng Ireland)' },
  { id: 'el', name: 'Tiếng Hy Lạp', instructionName: 'Greek (Tiếng Hy Lạp)' },
  { id: 'ko', name: 'Tiếng Hàn', instructionName: 'Korean (Tiếng Hàn)' },
  { id: 'ja', name: 'Tiếng Nhật', instructionName: 'Japanese (Tiếng Nhật)' },
  { id: 'fr-CA', name: 'Tiếng Pháp (Canada)', instructionName: 'Canadian French (Tiếng Pháp - Canada)' },
  { id: 'ru', name: 'Tiếng Nga', instructionName: 'Russian (Tiếng Nga)' },
  { id: 'tr', name: 'Tiếng Thổ Nhĩ Kỳ', instructionName: 'Turkish (Tiếng Thổ Nhĩ Kỳ)' },
];